=== tarasov1812/publico/XML-2/pagina.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="skills">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="informacion"/>
                <xs:element maxOccurs="unbounded" ref="texto"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="informacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo"/>
                <xs:element ref="autor"/>
                <xs:element ref="fecha"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="autor" type="xs:string"/>
    <xs:element name="fecha" type="xs:integer"/>
    <xs:element name="texto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="branch"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="branch">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="technology"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="technology" type="xs:string"/>
</xs:schema>

=== tarasov1812/publico/XML-2/pagina.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="pagina.xsl"?>
<skills xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pagina.xsd">
    <informacion>
        <titulo>THe most used</titulo>
        <autor>Programm</autor>
        <fecha>2023</fecha> 
    </informacion>

    <texto>
        <branch>
            <technology>Visual Studio Code</technology>
        </branch>
    </texto>

    <texto>
        <branch>
            <technology>Eclipse</technology>
        </branch>
    </texto>

    <texto>
        <branch>
            <technology>GitHubDesktop</technology>
        </branch>
    </texto>

    <texto>
        <branch>
            <technology>GoogleChrome</technology>
        </branch>
    </texto>

    <texto>
        <branch>
            <technology>Bash-Terminal</technology>
        </branch>
    </texto>

</skills>
